services:
  mysql:
    image: mysql:8.0
    container_name: fastfood-pagamentos-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fastfood_pagamentos
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - fastfood_pagamentos_db_data:/var/lib/mysql

volumes:
  fastfood_pagamentos_db_data: